dist: xenial
lang: go
notifications:
  irc:
    channels:
      - "chat.freenode.net#pkt"
    on_success: change
    on_failure: always
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - rpm
      go: 1.14.1
      script:
        - gem install --no-document fpm
        - bash -x ./contrib/deb/build.sh
        - bash -x ./contrib/rpm/build.sh
    - os: osx
      go: 1.14.1
      script:
        - gem install --no-document fpm
        - bash -x ./contrib/macos/build.sh