language: go
notifications:
  irc:
    channels:
      - "chat.freenode.net#pkt"
    on_success: change
    on_failure: always
branches:
  only:
  - master
  - develop
go:
  - "1.12.x"
sudo: false
script:
  - ./do
