language: go
branches:
  only:
  - master
  - pktd-mergeall
cache:
  directories:
    - $GOCACHE
    - $GOPATH
go:
  - "1.12.x"
sudo: false
install:
  - go build
  - go build -o wallet ./pktwallet
  - go build ./cmd/...
  - go test ./...
#  - go test -tags="rpctest" ./...
  - golangci-lint run --max-issues-per-linter 1000 --new-from-rev f158033947f8a658bab5001b0156168b85fcc70e
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./goclean.sh

